# Site settings
title: 马太目欢乐颂+
email: chany229@sina.com
description: "一个个人日记站"
baseurl: "http://chany229.github.io/dame09plus_jekyll"
url: "http://yourdomain.com"
twitter_username: jekyllrb
github_username:  chany229

# Build settings
markdown: kramdown
permalink: pretty



# for plugins
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']