# Site settings
title: 马太目欢乐颂+
email: chany229@sina.com
description: "一个个人日记站"
baseurl: "http://dame09.com"
url: "http://dame09.com"
twitter_username: jekyllrb
github_username:  chany229
# paginate: 1
# paginate_path: "list/page_:num"

# Build settings
markdown: kramdown
permalink: pretty



# for plugins
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
gems: ['jekyll-sass']